# LDA

In [2]:
import pandas as pd
import numpy as np
import random

In [3]:
df_copom = pd.read_csv('df_copom_label.csv')

In [5]:
df_copom = df_copom[df_copom['Type'] == 'Minutes']

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

C:\Users\ftrav\anaconda3\envs\pytorchenv\lib\site-packages\sklearn\utils\validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'
C:\Users\ftrav\anaconda3\envs\pytorchenv\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


In [7]:
cv = CountVectorizer(max_df=0.95, min_df=1, stop_words='english')

In [8]:
dtm = cv.fit_transform(df_copom['Text'])

In [9]:
dtm

<23x1910 sparse matrix of type '<class 'numpy.int64'>'
	with 9352 stored elements in Compressed Sparse Row format>

In [10]:
from sklearn.decomposition import LatentDirichletAllocation

C:\Users\ftrav\anaconda3\envs\pytorchenv\lib\site-packages\sklearn\linear_model\least_angle.py:35: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps,
C:\Users\ftrav\anaconda3\envs\pytorchenv\lib\site-packages\sklearn\linear_model\least_angle.py:597: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float

In [11]:
LDA = LatentDirichletAllocation(n_components=3,random_state=123)

In [12]:
LDA.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
             evaluate_every=-1, learning_decay=0.7,
             learning_method='batch', learning_offset=10.0,
             max_doc_update_iter=100, max_iter=10, mean_change_tol=0.001,
             n_components=3, n_jobs=None, n_topics=None, perp_tol=0.1,
             random_state=123, topic_word_prior=None,
             total_samples=1000000.0, verbose=0)

In [13]:
len(cv.get_feature_names())

1910

In [15]:
for i in range(10):
    random_word_id = random.randint(0,1910)
    print(cv.get_feature_names()[random_word_id])

mellomaurício
easing
adopting
ready
regulatory
mandate
august
evolves
away
exercises


In [16]:
len(LDA.components_)

3

In [17]:
len(LDA.components_[0])

1910

In [18]:
LDA.components_

array([[ 3.15464938,  0.33334159,  0.33333611, ...,  0.33333562,
         6.33332101,  2.33093657],
       [ 9.50801129,  0.55932442,  0.33333866, ...,  0.33333749,
         0.33333938,  0.33572165],
       [15.33733933,  2.10733399,  1.33332523, ...,  4.33332689,
         0.33333961,  0.33334178]])

In [19]:
single_topic = LDA.components_[0]

In [20]:
single_topic.argsort()

array([ 962,  954, 1209, ...,   37,   35,  943], dtype=int64)

In [21]:
top_word_indices = single_topic.argsort()[-10:]

In [22]:
for index in top_word_indices:
    print(cv.get_feature_names()[index])

cycle
period
greater
scenarios
tightening
pressures
uncertainty
2024
2023
inflationary


In [23]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names()[i] for i in topic.argsort()[-20:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['emphasizes', 'labor', 'deceleration', 'strategy', 'remain', 'quarter', 'impacts', 'longer', 'financial', 'continues', 'cycle', 'period', 'greater', 'scenarios', 'tightening', 'pressures', 'uncertainty', '2024', '2023', 'inflationary']


THE TOP 15 WORDS FOR TOPIC #1
['result', 'reference', 'pace', 'pandemic', 'upward', 'usd', 'scenarios', 'future', 'evolution', 'price', 'recovery', 'second', 'normalization', 'adjustment', '2021', 'regarding', 'tightening', 'appropriate', '2023', 'baseline']


THE TOP 15 WORDS FOR TOPIC #2
['sectors', 'transfer', 'remain', 'necessary', 'conditions', 'continue', 'financial', 'uncertainty', 'programs', 'regarding', '2020', 'slack', 'guidance', 'forward', 'evolution', 'stimulus', 'pandemic', 'recovery', '2021', 'baseline']




In [24]:
topic_results = LDA.transform(dtm)

In [25]:
topic_results[0].argmax()

2

In [26]:
topic_results.argmax(axis=1)

array([2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0], dtype=int64)

In [46]:
df_copom['LDA'] = topic_results.argmax(axis=1)
df_copom[['label_hawk_dove','LDA']]

label_hawk_dove  LDA
114          dovish    2
116         hawkish    2
118         neutral    2
120         neutral    2
122         neutral    2
123         hawkish    2
125         hawkish    1
128         hawkish    1
129         hawkish    1
131         hawkish    1
133         hawkish    1
135         hawkish    1
137         hawkish    1
140         hawkish    1
142         hawkish    0
144         hawkish    0
146         hawkish    0
147          dovish    0
150         neutral    0
152         neutral    0
153         neutral    0
155         neutral    0
158         neutral    0

# Non-Negative Matric Factorization

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
tfidf = TfidfVectorizer(max_df=0.95, min_df=1, stop_words='english')

In [30]:
dtm2 = tfidf.fit_transform(df_copom['Text'])

In [31]:
from sklearn.decomposition import NMF

In [32]:
nmf_model = NMF(n_components=3,random_state=123)

In [33]:
nmf_model.fit(dtm2)

NMF(alpha=0.0, beta_loss='frobenius', init=None, l1_ratio=0.0, max_iter=200,
  n_components=3, random_state=123, shuffle=False, solver='cd', tol=0.0001,
  verbose=0)

In [35]:
for i in range(10):
    random_word_id = random.randint(0,1910)
    print(tfidf.get_feature_names()[random_word_id])

yellow
simulations
contribute
pandemic
performed
weather
type
heightened
affairsrafael
backdrop


In [36]:
nmf_model.components_

array([[0.02193428, 0.        , 0.        , ..., 0.        , 0.04203587,
        0.02088891],
       [0.03795483, 0.0125453 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.09221501, 0.0166387 , 0.0150567 , ..., 0.04499229, 0.        ,
        0.        ]])

In [37]:
single_topic2 = nmf_model.components_[0]

In [38]:
top_word_indices2 = single_topic2.argsort()[-10:]

In [39]:
for index in top_word_indices2:
    print(tfidf.get_feature_names()[index])

deceleration
scenarios
impacts
pressures
cycle
tightening
uncertainty
2023
inflationary
2024


In [41]:
for index,topic in enumerate(nmf_model.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([tfidf.get_feature_names()[i] for i in topic.argsort()[-15:]])
    print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['continues', 'greater', 'emphasized', 'period', 'quarter', 'deceleration', 'scenarios', 'impacts', 'pressures', 'cycle', 'tightening', 'uncertainty', '2023', 'inflationary', '2024']


THE TOP 15 WORDS FOR TOPIC #1
['paths', 'pandemic', 'evolution', 'adjustment', 'second', 'recovery', 'normalization', 'regarding', 'upward', 'robust', 'tightening', 'appropriate', '2021', '2023', 'baseline']


THE TOP 15 WORDS FOR TOPIC #2
['government', 'service', 'financial', 'slack', 'evolution', 'transfer', 'programs', 'recovery', 'pandemic', 'stimulus', '2020', 'baseline', 'forward', '2021', 'guidance']




In [42]:
topic_results2 = nmf_model.transform(dtm2)

In [43]:
topic_results2.argmax(axis=1)

array([2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0], dtype=int64)

In [47]:
df_copom['NMF'] = topic_results2.argmax(axis=1)
df_copom[['label_hawk_dove','NMF']]

label_hawk_dove  NMF
114          dovish    2
116         hawkish    2
118         neutral    2
120         neutral    2
122         neutral    2
123         hawkish    2
125         hawkish    1
128         hawkish    1
129         hawkish    1
131         hawkish    1
133         hawkish    1
135         hawkish    1
137         hawkish    1
140         hawkish    1
142         hawkish    0
144         hawkish    0
146         hawkish    0
147          dovish    0
150         neutral    0
152         neutral    0
153         neutral    0
155         neutral    0
158         neutral    0