# SVM-chatgpt

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df_copom = pd.read_csv('df_copom_label.csv')

In [10]:
# df_copom.head()

In [11]:
# df_copom.iloc[29]

In [12]:
# df_copom.shape

In [18]:
texts = df_copom['Text'].tolist()
labels = df_copom['label_hawk_dove']

In [19]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

def preprocess_text(text):
    # Remove special characters and numbers
    text = re.sub(r'\W+', ' ', text)
    
    # Convert to lowercase
    text = text.lower()
    
    # Tokenization
    tokens = text.split()
    
    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    tokens = [word for word in tokens if word not in stop_words]
    
    # Lemmatization
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    
    # Join tokens back into a single string
    preprocessed_text = ' '.join(tokens)
    
    return preprocessed_text

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ftrav\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ftrav\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report

In [27]:
# Preprocess the text data and extract labels
preprocessed_text = []

for i, text in enumerate(texts):
    preprocessed_text.append(preprocess_text(text))

labels = df_copom['label_hawk_dove']

In [29]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(preprocessed_text, labels, test_size=0.2, random_state=42)

In [30]:
# Perform feature extraction using TF-IDF vectorization
vectorizer = TfidfVectorizer()
X_train_features = vectorizer.fit_transform(X_train)
X_test_features = vectorizer.transform(X_test)

In [31]:
# Train an SVM classifier
svm_classifier = SVC(kernel='linear')
svm_classifier.fit(X_train_features, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [32]:
# Predict labels for the test set
y_pred = svm_classifier.predict(X_test_features)

In [33]:
# Evaluate the classifier
report = classification_report(y_test, y_pred)
print(report)

              precision    recall  f1-score   support

      dovish       0.80      0.67      0.73         6
     hawkish       0.79      0.92      0.85        12
     neutral       0.85      0.79      0.81        14

   micro avg       0.81      0.81      0.81        32
   macro avg       0.81      0.79      0.80        32
weighted avg       0.81      0.81      0.81        32



In [35]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,y_pred))

[[ 4  1  1]
 [ 0 11  1]
 [ 1  2 11]]


In [36]:
print(metrics.accuracy_score(y_test,y_pred))

0.8125
